[package]
name = "aoc-template"
version = "2021.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.0"
itertools = "0.10.1"
clap = "2.33.3"
chrono = "0.4.19"